export const ALL_SERVICES = [
  "General Cleaning",
  "Deep Cleaning",
  "Housekeeping",
  "Plumbing Repair",
  "Clogged Drain Clearing",
  "Faucet Installation",
  "Electrical Repair",
  "Lighting Installation",
  "Appliance Repair",
  "Aircon Cleaning",
  "Aircon Repair",
  "Carpentry",
  "Furniture Assembly",
  "Interior Painting",
  "Exterior Painting",
  "Gardening",
  "Lawn Mowing",
  "Pest Control",
  "Home Moving",
  "Junk Removal",
  "Laundry Service",
  "Errand Running",
  "Grocery Shopping",
  "Pet Sitting",
  "Dog Walking",
  "Tech Support",
  "Laptop Repair",
  "Academic Tutoring",
  "Music Lessons",
  "Graphic Design",
  "Video Editing",
  "Event Planning",
  "Catering",
  "Personal Training",
  "Yoga Instruction",
  "Photography",
  "Makeup Artist",
  "Car Wash",
  "Nail Service",
  "Massage Therapy"
];

export const COMMON_SERVICES = [
  "General Cleaning",
  "Deep Cleaning",
  "Plumbing Repair",
  "Electrical Repair",
  "Aircon Cleaning",
  "Carpentry",
  "Gardening",
  "Home Moving",
  "Tech Support",
  "Laundry Service"
];
